name: novatech_chat
description: Technical Challenge for NovaTech
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.9
  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  shadcn_ui: ^0.27.2

dev_dependencies:
  bloc_test: ^9.1.7
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/
